astral-sh/rye

rye/src/bootstrap.rs, rye/src/cli/add.rs, rye/src/cli/init.rs, rye/src/cli/show.rs, rye/src/installer.rs, rye/src/lock.rs, rye/src/pyproject.rs, rye/src/sources.rs, rye/src/sync.rs
Hi! Cool project! This PR resolves:
```zsh
rye on  clippy via 🦀 v1.69.0 
❯ cargo clippy
```
=> Clippy lints

README.md
=> Fix spelling error and improve grammar in READEME.md

README.md, rye/src/cli/shim.rs, rye/src/config.rs, rye/src/pyproject.rs
Fix a few typos, no functional changes.
=> Fix some typos

rye/src/bootstrap.rs, rye/src/cli/shim.rs, rye/src/utils.rs
Fixes #8
An alternative would be to hardlink on linux which is what busybox does.
=> Detect symlinks properly on linux in shims

README.md, rye/src/cli/toolchain.rs
Corrects two typos in the repository.
=> Correct two typos

CHANGELOG.md, rye/src/cli/add.rs
=> Add pre flag to add command

rye/src/bootstrap.rs, rye/src/lock.rs, rye/src/sync.rs
Horrible temporary workaround for #82
=> Ugly hack to link pip-tools on demand into the venv

rye/src/bootstrap.rs, rye/src/lock.rs, rye/src/main.rs, rye/src/piptools.rs, rye/src/pyproject.rs, rye/src/sync.rs
This is a better workaround until I get time to ditch pip-tools.
Fixes #104.
=> Create cached virtualenvs for pip-tools

CHANGELOG.md, Cargo.lock, rye/Cargo.toml, rye/src/cli/init.rs
create an license file when init.
=> add feature when init create license file

docs/faq.md, docs/guide.md, docs/index.md, mkdocs.yml
And remove the `$` symbol for better copying.
=> Change docs for better user experience

CHANGELOG.md, rye/src/cli/init.rs, rye/src/installer.rs
=> support install global isolated tools with python 3.7 toolchain

rye/src/bootstrap.rs, rye/src/cli/init.rs, rye/src/config.rs, rye/src/installer.rs, rye/src/main.rs, rye/src/piptools.rs, rye/src/platform.rs, rye/src/pyproject.rs, rye/src/sync.rs
For now it does not configure much, but it creates a path for more customizability.
=> Add a config.toml file for rye

Cargo.lock, rye/Cargo.toml, rye/src/bootstrap.rs, rye/src/cli/toolchain.rs, rye/src/installer.rs, rye/src/utils.rs
When symlinks don't work, we fall back to junctions or hardlinks.
Refs #131
=> Use junctions as fallback on windows

rye/src/cli/toolchain.rs, rye/src/platform.rs
=> Also allow registration of toolchains without symlinks

rye/src/installer.rs
=> Uninstall scripts when hardlinks are used

docs/guide/sync.md
Fixes two docs typos: synching -> syncing
=> Fix: doc typos

mkdocs.yml
again, changes synching for syncing. Missed this in last PR
=> Fix: missed typo

.github/workflows/release.yml, scripts/install.sh
Changes CI to gzip binaries on non windows platforms.
=> Gzip binaries

CHANGELOG.md, rye/src/cli/rye.rs, rye/src/main.rs
This helps actually seeing the error if something goes wrong.
=> Ask for a key press on windows in self install

rye/src/cli/init.rs
https://pdm-backend.fming.dev/
Maybe we should also support PDM backend.
=> Support pdm build backend

CHANGELOG.md, Cargo.lock, rye/Cargo.toml, rye/src/cli/rye.rs
=> Fixed bug with uninstall on macos

.github/workflows/release.yml
=> Modified CI setup

CHANGELOG.md, docs/guide/deps.md, rye/src/cli/add.rs
=> Documented --pre flag and added improved warning

rye/src/bootstrap.rs, rye/src/cli/rye.rs
=> Update core shims after an update

.github/workflows/release.yml, scripts/sha256.py, scripts/summarize-release.py
This publishes releases with a manifest. Fixes #222
=> Write release manifest

CHANGELOG.md, rye/src/bootstrap.rs, rye/src/cli/rye.rs, rye/src/utils.rs
For releases that have checksums, validate them on update.
=> Validate checksum of downloaded update

rye/src/cli/init.rs
fixes https://github.com/mitsuhiko/rye/issues/243
=> Add newline before [tool.hatch.metadata]

CHANGELOG.md, pyproject.toml, rye/src/pyproject.rs, rye/src/utils.rs
=> Reformat dependencies in pyproject.toml after modification to multi-line

rye/src/pyproject.rs, rye/src/sources.rs
=> Fix pin command pinning incorrect version

CHANGELOG.md
=> Added changelog entry for --pyproject

rye/src/cli/toolchain.rs
The intention is to use this with tools and plugins that would get python versions from rye, maybe for example Tox.
With the PR, `rye toolchain list --format=json --include-downloadable` outputs something like this:
```json
[
{
"name": "cpython@3.11.3",
"path": "/home/user/.rye/py/cpython@3.11.3/install/bin/python3"
},
{
"name": "pypy@3.9.16",
"path": "/home/user/.rye/py/pypy@3.9.16/bin/python3"
},
{
"name": "cpython@3.10.9",
"downloadable": true
},
// more lines omitted
]
```
"name" seems apt for the version field as long as it is the verbatim version name rye uses. Maybe it should be broken up into implementation and version number fields.
=> Add json output for rye toolchain list

docs/guide/publish.md, mkdocs.yml
closes https://github.com/mitsuhiko/rye/issues/201
=> Add docs for build and publish parts

CHANGELOG.md, rye/src/cli/build.rs
This did not invoke the interpreter correctly.
=> Fix rye build on windows

rye/src/pyproject.rs
Now members = [] means no members, while missing members key means
everything is a member.
Update members glob settings:
backslash_escape has a default that depends on platform. pyproject.toml
should have the same meaning regardless of platform, so it can't be
used. Example without backslash: literal `*` is matched by using `[*]`.
`*` and `?` not matching directory separators is an opinionated choice
to be more explicit about which members match.
Case insensitive is not set here, but it could also be set. It would make
some optimizations harder (only search literally named paths, when possible?)
=> Workspace: Fix meaning of members=[] and glob settings

CHANGELOG.md, Cargo.lock, docs/guide/config.md, rye/src/config.rs
=> Renamed misnamed config keys

CHANGELOG.md, docs/guide/config.md, docs/guide/shims.md, rye/src/cli/config.rs, rye/src/cli/mod.rs, rye/src/config.rs
Makes it possible to change the config from the command line.
=> Added config manipulation command

docs/guide/shims.md
=> Update shims.md - small typo

CHANGELOG.md, rye/src/cli/init.rs
=> Do not create src folder on import

CHANGELOG.md, docs/guide/config.md, rye/src/cli/init.rs, rye/src/config.rs, rye/src/platform.rs
The author can now be configured with `default.author`.
Fixes #376
=> Add support for configuring the author

CHANGELOG.md, scripts/install.sh
=> Detect noexec /tmp

rye/src/cli/tools.rs, rye/src/installer.rs
```
➜  ~ rye tools list -v
black 23.3.0
daecli 0.7.14
hatch 1.7.0
ipython 8.14.0
pytest 7.4.0
rich-cli 1.8.0
ruff 0.0.281
```
=> Can show the version of tools

rye/find-downloads.py
=> add support for pypy@3.10

CHANGELOG.md, rye/src/bootstrap.rs
=> The fallback shim installation on Linux now uses copy

docs/philosophy.md
✏️ Fix micro-typo in` docs/philosophy.m`
=> ✏️ Fix micro-typo in` docs/philosophy.m`

rye/src/cli/build.rs
Fixed https://github.com/mitsuhiko/rye/issues/475
=> Fix the error when build with --clean

docs/guide/installation.md
=> Add docs for shell completion

docs/guide/installation.md
=> Fix typo in installation.md

.github/workflows/release.yml
Whilst adapting your workflow for my own nefarious purposes (thanks), I found this was broken 😄
=> Fix release.yml dry run

CHANGELOG.md, pyproject.toml, rye/src/cli/init.rs, rye/src/pyproject.rs, rye/src/sync.rs
=> Fix bad project setup for hatch

CHANGELOG.md, rye/src/platform.rs
=> Correctly fall back to home folder if HOME is unset

CHANGELOG.md, rye/src/pyproject.rs, rye/src/sync.rs
=> Detect relocated virtualenv

CHANGELOG.md, rye/src/cli/shim.rs
=> Fix an issue where global python shims did not honor .python-version

CHANGELOG.md, docs/guide/basics.md, rye/src/cli/mod.rs
=> Add a helpful error message if someone invokes rye list

CHANGELOG.md, rye/src/bootstrap.rs, rye/src/cli/add.rs
This regressed in 0.18.
Fixes #546
=> Fix a regression in the add command

CHANGELOG.md, rye/src/cli/rye.rs
=> Improve error message on failed updates

rye/src/cli/shell.rs
A minor improvements to reuse `consts::VENV_BIN`.
=> Reuse `consts::VENV_BIN`

CHANGELOG.md, rye/src/cli/shell.rs
The shell is currently quite buggy. Until fixed add a warning.
Refs #73
=> Add a warning to the console command about bugs

Cargo.lock, rye/Cargo.toml
=> Bump monotrail

rye/src/sync.rs
=> Use create_dir_all to create virtualenvs

CHANGELOG.md, docs/guide/commands/list.md, docs/guide/commands/show.md, rye/src/cli/list.rs, rye/src/cli/mod.rs, rye/src/cli/show.rs
This replaces the `show --installed-deps` command with just `list`.
=> Replace show --installed-deps with list

CHANGELOG.md, rye/src/bootstrap.rs, rye/src/config.rs
This adds support of uv on windows and bumps it to 1.0.3
=> Enable uv on windows too

rye/src/config.rs
Added tests to `config.rs` to cover loading configs, defaults, behavior flags, and proxy settings.
=> added tests for config.rs

CHANGELOG.md, rye/src/bootstrap.rs
=> bump uv to 0.1.5

CHANGELOG.md, rye/src/bootstrap.rs
=> Bump bundled ruff to 0.2.2

rye/tests/common/mod.rs, rye/tests/test_tools.rs
=> Added basic tools behavior test

rye/src/bootstrap.rs
=> Improve the consistency of installation messages

CHANGELOG.md, rye/src/bootstrap.rs
=> bump uv to 0.1.6

CHANGELOG.md, rye/src/cli/add.rs, rye/tests/common/mod.rs, rye/tests/test_add.rs
This fixes a bug where `add` did not honor custom sources with `uv` is enabled.
=> Fix custom sources not working with add

.github/workflows/docs.yml, CHANGELOG.md, docs/guide/commands/tools/list.md, rye/src/cli/tools.rs, rye/tests/test_tools.rs
=> Rename `rye tools list` flags

rye/src/bootstrap.rs, rye/src/cli/build.rs, rye/src/cli/init.rs, rye/src/cli/pin.rs, rye/src/cli/rye.rs, rye/src/cli/toolchain.rs, rye/src/config.rs, rye/src/installer.rs, rye/src/lock.rs, rye/src/piptools.rs, rye/src/platform.rs, rye/src/pyproject.rs, rye/src/sync.rs, rye/src/utils/mod.rs, rye/src/utils/unix.rs, rye/tests/common/mod.rs
=> Improve the reporting of IO errors

docs/.includes/quick-install.md
Minor document grammar correction.
=> docs: correcting grammar

rye/src/lock.rs, rye/tests/test_add.rs, rye/tests/test_init.rs, rye/tests/test_sync.rs
=> Fix a warning about empty requirements file

CHANGELOG.md, rye/src/lock.rs, rye/tests/common/mod.rs, rye/tests/test_add.rs
=> Fix rye failing if a bad VIRTUAL_ENV is exported

CHANGELOG.md, rye/src/bootstrap.rs, rye/src/sync.rs, rye/src/uv.rs, rye/tests/common/mod.rs, rye/tests/test_sync.rs
Adds `--prompt` support to virtualenvs created with uv.
=> Add --prompt support to uv venv

docs/guide/installation.md
Minor doc changes for `.zprofile` and `.zshrc` for adding shims to path.
=> docs: updating shim instruction for zsh

docs/guide/commands/init.md
Add SPDX identifier link in init.md
=> Add SPDX identifier link in init.md

CHANGELOG.md, rye/src/cli/add.rs, rye/tests/common/mod.rs, rye/tests/test_add.rs, rye/tests/test_sync.rs
=> Retain markers

CHANGELOG.md, rye/src/templates/pyproject.toml.j2, rye/tests/test_init.rs
Refs #796
Needs doc updates still.
=> Fix the script name to be the project name

pyproject.toml, requirements-dev.lock, requirements.lock
Virtual root because it has no python package.
Update lockfile - includes changes due to previous changes (pytest).
=> Make rye-dev package virtual

CHANGELOG.md, rye/src/bootstrap.rs
=> Update build and certify

rye/src/cli/init.rs
fixes https://github.com/astral-sh/rye/issues/889
=> Always create .gitignore file

rye/tests/test_version.rs
Prepare for https://github.com/astral-sh/rye/issues/753, added basic version command tests.
=> Added basic version command tests

rye/Cargo.toml
=> Fix windows builds

docs/guide/config.md
Noticed a couple of typos, and places where I thought the wording could be made a bit clearer.
=> doc: Typos and wording

Cargo.lock, rye/Cargo.toml, rye/src/cli/init.rs
=> Update minijinja to 2.x

rye/Cargo.toml
=> Add missing features for windows build

rye/src/cli/rye.rs
Closes https://github.com/astral-sh/rye/issues/1124.
=> Fix CLI deserialization of PowerShell (powershell)

docs/guide/faq.md, docs/guide/toolchains/cpython.md
Closes https://github.com/astral-sh/rye/issues/1176.
=> Update links to behavior quirks guide

docs/guide/sources.md
=> docs: add hint for packages on multiple indexes

rye/src/utils/windows.rs
make uninstall_cmd available in Windows
=> uninstall_cmd fix in Windows

docs/guide/docker.md
The Dockerfile code example was broken for me - this PR fixes this error.
=> Fix Docker code example
