rye/src/sources.rs
From my testing, the `test_get_download_url` fails with:
```
Running unittests src/main.rs (target/x86_64-unknown-linux-gnu/release/deps/rye-f2fb693ac01ef08b)
running 1 test
test sources::test_get_download_url ... FAILED
failures:
---- sources::test_get_download_url stdout ----
thread 'sources::test_get_download_url' panicked at 'assertion failed: `(left == right)`
left: `Some((PythonVersion { kind: "cpython", major: 3, minor: 8, patch: 14 }, "https://github.com/indygreg/python-build-standalone/releases/download/20221002/cpython-3.8.14%2B20221002-aarch64-apple-darwin-pgo-full.tar.zst"))`,
right: `Some((PythonVersion { kind: "cpython", major: 3, minor: 8, patch: 14 }, "https://github.com/indygreg/python-build-standalone/releases/download/20221002/cpython-3.8.14%2B20221002-aarch64-apple-darw …
```
=> sources.rs: fix test_get_download_url

README.md
Just a tiny typo that could confuse someone who is copy pasting there way into a trial run.
=> Fix: typo in first readme command

Cargo.lock, rye/Cargo.toml
This change configures anyhow to automatically generate backtraces. This enables using `RUST_BACKTRACE=1` to see a backtrace on any scenario where an unhandled Error is returned.
=> Enable anyhow's backtrace support

README.md
Placed `Some of the things it does` after  `Installation`. It makes sense to have installation come after describing a summary of what `Rye`is. Most developers after reading the summary will rush to find out how to quickly install so found that something to refactor.
=> Minor refactoring of README

README.md
The PR adds a description of  `rye toolchain list --include-downloadabl` option.
https://github.com/mitsuhiko/rye/issues/50
=> Add downloadable toolchain option to document

rye/src/utils.rs
This PR adds unit tests for the following:
- `CommandOutput` verbose and quiet implementation
- `QuietExit` display implementation
- `format_requirement` function with:
- Simple requirement (name and version specifier)
- Complex requirement (name, extras, version specifier, and marker)
- File path requirement
- `expand_env_vars` function with:
- String without environment variables
- String containing an environment variable for expansion
```bash
➜ cargo test
Compiling rye v0.1.0 (/Users/seba/Dropbox/code/rye/rye)
Finished test [unoptimized + debuginfo] target(s) in 1.56s
Running unittests src/main.rs (target/debug/deps/rye-4d0f8df5e35626e9)
running 10 tests
test utils::test_command_output::test_command_output_defaults ... ok
test …
```
=> Add tests for utility functions and implementations

CHANGELOG.md, rye/src/cli/pin.rs, rye/src/pyproject.rs
Closes #74
This PR currently updates requires-python in pyproject.toml if the version pinned is older than the marked requires-python version.
```zsh
❯ rye pin 3.11      # doesn't change anything in a ">= 3.10" marked project
❯ rye pin 3.8       # updates the requires-python in the toml to ">= 3.8" 
```
________
**Alternatively** we could provide the following [experience](https://github.com/mitsuhiko/rye/pull/75#issuecomment-1529034966):
```zsh
❯ rye pin 3.11      # doesn't change anything in a ">= 10" marked project
❯ rye pin 3.8       # fails similar to pip install <packages> in a ">= 3.10" marked project
❯ rye pin 3.8 -f    # updates the requires-python in the toml to ">= 3.8"
```
I can add [those changes](https://github.com/cnpryer/rye/compare/pin-requires-python...cnpryer:rye:pin-req …
=> Update pyproject.toml with new pinned Python

rye/Cargo.toml
There are systems that don't have openssl-dev files on them. Making openssl a static dependency of curl makes it easier to build and run rye
=> Update curl crate to include openssl as a static dep

rye/src/cli/init.rs
I noticed that `--license` was missing a help message description, so I added one.
=> Add help message for init --license

rye/src/cli/init.rs
The user should be able to specify the name of the package. This would be good for those cases where the project name and the final package do not match 😄.
=> Add option package name when init

CHANGELOG.md, rye/src/cli/init.rs, rye/src/cli/show.rs, rye/src/config.rs, rye/src/pyproject.rs, rye/src/sources.rs, rye/src/sync.rs
This makes Rye more consistently work with Python versions. Before when a new venv was created, the latest cpython version was used in all cases and 3.8 was set as lower bound in the `pyproject.toml`.
Now the following logic applies:
* When creating a new project, `.python-version` is written and points to the latest cpython version. The `requires-python` key is set to `3.8` by default.
* When a virtualenv is created, `.python-version` is preferred, otherwise it falls back to `requires-python`.
This now also means that `.python-version` is entirely optional if you want to keep them in sync.
Refs #96
=> More consistent python version handling

docs/commands.md, docs/guide.md
https://github.com/mitsuhiko/rye/blob/30c9e01aa123c18f7e00dbad91737907545bed7e/docs/index.md?plain=1#L20-L21
Was looking at merging `main` into my `publish` branch and noticed 30c9e01aa123c18f7e00dbad91737907545bed7e yanked the user guide and features files, but I'm not sure if you meant to do this instead of just changing the file names.
If you want those back I've added them to this PR as `commands.md` and `guide.md`.
=> Fix dead links in docs

CHANGELOG.md, rye/src/cli/run.rs, rye/src/pyproject.rs, rye/src/utils.rs
This adds support for script chaining and environment variables like so:
```toml
[tool.rye.scripts]
serve = { cmd = "flask run", env = {"FLASK_APP" = "./hello.py"} }
lint = { chain = ["lint:black", "lint:flake8" ] }
"lint:black" = "black --check src"
"lint:flake8" = "flake8 src"
```
With this you can run `rye run lint` to invoke first `rye run lint:black` followed by `rye run lint:flake8` if the first script did not fail. This really needs docs.
Output in list:
```
lint (chain: [lint:black], [lint:flake8])
lint:black (black --check src)
lint:flake8 (flake8 src)
serve (FLASK_APP=./hello.py flask run)
```
Fixes #152
=> Added support for script chaining and env vars

CHANGELOG.md, rye/src/cli/add.rs, rye/src/cli/init.rs, rye/src/pyproject.rs
fixes https://github.com/mitsuhiko/rye/issues/158
Test:
```
➜  o git:(main) ✗ rye add --git https://github.com/pallets/flask.git --branch main flask
Added flask @ git+https://github.com/pallets/flask.git@main as regular dependency
➜  o git:(main) ✗ rye add --path ../../isort-5.12.0-py3-none-any.whl isort
Added isort @ file:///Users/zhezhezhu/projects/test/o/../../isort-5.12.0-py3-none-any.whl as regular dependency
```
=> Support direct references when add package

CHANGELOG.md, rye/src/cli/init.rs
closes https://github.com/mitsuhiko/rye/issues/160
=> Support auto fix requires-python when conflict

CHANGELOG.md, Cargo.lock, docs/guide/faq.md, rye/Cargo.toml, rye/src/bootstrap.rs, rye/src/cli/mod.rs, rye/src/cli/rye.rs, rye/src/platform.rs
This adds a helpful message to the installer when symlinks are unavailable on windows.
Fixes #203
Fixes #204
=> Detect symlink behavior and document it better

rye/src/cli/publish.rs
Didn't realize this originally, but `--repository` and `--repository-url` have redundant "default" info.
Currently you'll get
```
❯ rye publish -h
Publish packages to a package repository
Usage: rye publish [OPTIONS] [DIST]...
Arguments:
[DIST]...  The distribution files to upload to the repository (defaults to
<workspace-root>/dist/*)
Options:
-r, --repository <REPOSITORY>
The repository to publish to (defaults to 'pypi') [default: pypi]
--repository-url <REPOSITORY_URL>
The repository url to publish to (defaults to
https://upload.pypi.org/legacy/) [default:
https://upload.pypi.org/legacy/]
--token <TOKEN>
An access token used for the upload
--sign
Sign files to upload using GPG
-i, --identity <IDENTITY>
GPG identity used to sign files
--cert <CERT>
Path to alternate CA bundle
-v, …
```
=> Remove redundant publish arg descriptions

CHANGELOG.md, rye/src/cli/publish.rs
Some package repositories need a `username` to upload packages, for example Google Artifact Register use `_json_key_base64` as a username: https://cloud.google.com/artifact-registry/docs/python/authentication
Tested with:
```
rye publish -r google --repository-url https://asia-northeast1-python.pkg.dev/shaped-infusion-348103/test/ --username _json_key_base64 --token ...
```
=> Add username args for rye publish

rye/src/installer.rs
I can still see it with `rye tools list` after a failed install with `rye install hakuna`. It looks like this is caused by not cleaning up after the failure.
Before:
```
➜  o git:(main) ✗ rye tools install hakuna
ERROR: Could not find a version that satisfies the requirement hakuna (from versions: none)
ERROR: No matching distribution found for hakuna
Error: tool installation failed
➜  o git:(main) ✗ rye tools list
hakuna
...
```
After:
```
➜  o git:(main) ✗ rye tools install hakuna
ERROR: Could not find a version that satisfies the requirement hakuna (from versions: none)
ERROR: No matching distribution found for hakuna
Error: tool installation failed
➜  o git:(main) ✗ rye tools list
...
```
=> Fix the issue where tools that failed to install still appear

rye/src/cli/init.rs, rye/src/sources.rs
fixes https://github.com/mitsuhiko/rye/issues/231.
This was originally caused by https://github.com/mitsuhiko/rye/pull/202.
=> Fix invalid version error when using  rye init with custom toolchain

docs/guide/faq.md, rye/src/sync.rs
This is a creative workaround for #226
The downside is that it exports two environment variables into all python processes on unix, but maybe that's reasonable.
=> Emit a PTH file to find TCL

CHANGELOG.md, rye/src/installer.rs
We need this feature to install global tools from a custom index. 
``` 
➜ ~ rye install daecli 
Looking in indexes: https://pypi.sapps.douban/simple, https://pypi.org/simple/ 
Collecting daecli
......
```
=> Support install tools from custom indexes

rye/src/cli/rye.rs
current_exe resolves the symlink /proc/self/exe on linux, and it correctly points to a now-deleted file after self replacement, and produces an error.
Read the current exe path before replacing to avoid this error.
Fixes #251
=> Read current_exe path before self update (#251)

scripts/install.sh
I added `RYE_INSTALL_OPTION` environment variable to override the install option via install.sh script.
Solve https://github.com/mitsuhiko/rye/issues/246
Expected usage
```dockerfile
FROM python:3.11
ENV RYE_INSTALL_OPTION=-y
RUN curl -sSf https://rye-up.com/get | bash
CMD ["python3"]
```
=> allow overriding the install option via install.sh

rye/src/cli/init.rs
Spelling `Filt` made it impossible to init a project to use flit.
=> Fix rye init for flit

CHANGELOG.md, docs/guide/config.md, rye/src/cli/add.rs, rye/src/cli/init.rs, rye/src/config.rs, rye/src/pyproject.rs
closes https://github.com/mitsuhiko/rye/issues/244
```
➜  o git:(main) ✗ cat ~/.rye/config.toml
[default]
build-system = "pdm"
license = "MIT"
[[sources]]
name = "dou"
url = "https://pypi.sapps.douban/simple"
➜  o git:(main) ✗ rye init
success: Initialized project in /Users/zhezhezhu/projects/test/o/.
Run `rye sync` to get started
(douban) ➜  o git:(main) ✗ cat pyproject.toml
[project]
name = "o"
version = "0.1.0"
description = "Add a short description here"
authors = [
{ name = "Chaojie", email = "hi@chaojie.fun" }
]
dependencies = []
readme = "README.md"
requires-python = ">= 3.11"
license = { text = "MIT" }
[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"
[tool.rye]
managed = true
```
=> Default build-system and license can be specified in global config

rye/src/pyproject.rs
Skip .venv since it can contain stray pyprojects that are not related to
the current project. Further items could be ignored here.
Correctness fix (previously pyproject.toml installed into some package
in the environment, could ruin the sync), as well as a speed up since we
can skip scanning all the files in the environment.
Also change the order of member check and loading the project, it
seemed better to me in this order.
Fixes #260
=> Skip .venv and .git when searching workspace

CHANGELOG.md, docs/guide/toolchains/index.md, rye/src/cli/toolchain.rs
A take on a part of #267. If a debug build is registered, the name is automatically adjusted.
=> Add -dbg to the toolchain name for debug builds

rye/src/cli/publish.rs
We should add a parameter for publish command with no prompt, this benefit for some CI environments (They usually can't use prompt).
The word `--yes` comes from `rye self install --yes`, I'm not sure this is appropriate.
=> Add --yes parameter for rye publish

CHANGELOG.md, docs/.includes/curl-to-bash-options.md, docs/.includes/installer-options.md, docs/guide/installation.md, rye/src/bootstrap.rs, rye/src/cli/mod.rs, rye/src/cli/rye.rs, rye/src/cli/shim.rs, rye/src/cli/toolchain.rs, rye/src/sources.rs, rye/src/sync.rs
Hello,
I really *love* rye's user XP. This is *so* refreshing...
This patch:
* make `matches_version()` public.
* add `ensure_toolchain(&PythonVersionRequest)`.
* allow using preregistered toolchains for rye's self environments.
This is very useful in places where downloading a python build from random other places is a no no, because fighting corporate proxies & firewalls to get job done is no fun (hello zscaler).
Oh, also, as a bonus, this adds an option `--dbg` to `toolchain register` command`:
```
rye toolchain register --dbg /path/to/your/python/with/debug/symbols
```
Regards,
Charbel
=> Allow using system python for self environment

rye/Cargo.toml
Build phase on NixOS does not have access to the network so to build the application it must be patched
=> Make it more friendly to build on NixOS

rye/src/cli/pin.rs, rye/src/pyproject.rs
These are some small changes found on the way to working on #232: Additional error context if reading a pyproject.toml file fails ("permission denied" etc) and error reporting for pin.
=> Smaller pyproject changes: error reporting in reading, in pin

CHANGELOG.md, rye/src/cli/mod.rs, rye/src/cli/version.rs, rye/src/pyproject.rs
closes https://github.com/mitsuhiko/rye/issues/285
```
➜  o git:(main) ✗ rye version
0.1.0
➜  o git:(main) ✗ rye version 0.2.0
version set to 0.2.0
```
=> Support version command for rye

rye/src/cli/build.rs, rye/src/cli/init.rs, rye/src/cli/pin.rs, rye/src/cli/run.rs, rye/src/cli/shell.rs, rye/src/cli/show.rs, rye/src/cli/sync.rs, rye/src/platform.rs, rye/src/pyproject.rs, rye/src/sync.rs
This enables using rye outside of its project home.
Some refactoring to make rye less sensitive to its current working directory:
1. `.python-version` searching is now relative to `pyproject.toml` if we have a project
2. PyProject saves the filename (so that it can write the same filename again later in add, remove, pin)
SyncMode::PythonOnly can support a custom pyproject location for now. The rest of the lock/sync
machinery would need more work. PythonOnly sync is needed to support `rye run` and `rye shell`.
```
rye run --pyproject ./path/to/project/pyproject.toml python3
rye show --pyproject <a project.toml>
```
I'd like to add `--pyproject` to every applicable command. But these are left and need resolution later:
-  `lock` and `sync`: relative path logic, `pyproject.toml` default for …
=> pyproject location argument for rye run, shell, show, build, pin

rye/src/cli/init.rs
PyPI recognizes this marker for private projects and will refuse upload.
Documented in https://pypi.org/classifiers/ and https://flit.pypa.io/en/stable/pyproject_toml.html
=> Add rye init --private

rye/src/lock.rs
pip currently is excuted in the working directory of rye.  This means that pip cannot find the appropriate pyproject and will fail to write the requirements.lock. We now explicitly call pip in the determined workspace_path.
Please note this is an early PR and my first change. I don't fully understand the rye codebase yet and have not extensively tested this change yet. So beware, there might be dragons.
Currently this has been tested doing the following:
```
$ rye init root
success: Initialized project in /home/dsp/src/root
Run `rye sync` to get started
$ cd root
$ rye init submodule
success: Initialized project in /home/dsp/src/root/submodule
Run `rye sync` to get started
$ echo "[tool.rye.workspace]\nmembers=[\"submodule\"]" >> pyproject.toml
$ cd submodule
$ rye sync
```
```
Generating …
```
=> Run pip in workspace root (#284)

CHANGELOG.md, rye/src/cli/build.rs
It would be useful to add a `clean` parameter to the `build` command if I just need the current latest build target.
=> Add --clean for build command

rye/src/pyproject.rs
It looks to me like the relative path is always empty. I'm not 100% sure what the intention was here with the canonicalization.
With this fix, limiting members using an explicit list in the workspace should work better. Previously it seemed to include everything in all cases.
rye show is the quickest way to see the workspace member list, but it affects rye lock foremost (with bad effects if it includes stray projects.)
Reproduce:
```shell
rye init workspace
cd workspace
echo "[tool.rye.workspace]" >> pyproject.toml
echo 'members = ["a"]' >> pyproject.toml
rye init a
rye init b
rye show
```
Expected: Workspace is root and a. Actual: Workspace was root, a, and b.
=> workspace is member: fix relative path

CHANGELOG.md, rye/src/cli/version.rs
https://github.com/mitsuhiko/rye/issues/285
```
➜  o git:(main) ✗ rye version
0.1.0
➜  o git:(main) ✗ rye version 0.2.0
version set to 0.2.0
➜  o git:(main) ✗ rye version --bump major
version bumped to 1.2.0
➜  o git:(main) ✗ rye version --bump minor
version bumped to 1.3.0
➜  o git:(main) ✗ rye version --bump patch
version bumped to 1.3.1
➜  o git:(main) ✗ rye version --bump ooo
```
=> Add --bump for version command

rye/src/cli/mod.rs
```
➜  ~ rye -h
An Experimental Package Management Solution for Python
Usage: rye [COMMAND]
Commands:
add        Adds a Python package to this project
```
=> Add cli description

rye/src/cli/lock.rs, rye/src/cli/sync.rs, rye/src/sync.rs
Add the --pyproject argument for rye sync and rye lock.
Sync, lock will only work if the file is literally called pyproject.toml in the filename, because that's what pip-tools expect. Further meditation over this maybe makes any other name than `pyproject.toml` unnatural, most tools are quite insistent that this is the only valid name (?). If rye would have the same opinion, then we could consider changing all these arguments to `--project <directory>` instead.
=> sync, lock: --pyproject argument

rye/src/lock.rs, rye/src/sync.rs
Set PROJECT_ROOT as env variable both for pip-compile and pip-sync. pdm does the equivalent of not using any leading slash in its replacement (We could see that `file:////` triggered an error(!)).
If PROJECT_ROOT is set like this, relative paths inside and outside of the project work :slightly_smiling_face: 
Here's how to setup the project:
```shell
#!/bin/sh
rye init sibling
rye init project_root --build-system pdm
cd project_root
rye init lib/a
rye init lib/b --build-system pdm
rye add --path ../sibling sibling
rye add --path ./lib/a a
rye add --path ./lib/b b
```
With this PR we can successfully `cd project_root; rye sync -v` 
The pyproject ends up with these dependencies for reference:
```toml
dependencies = [
"sibling @ file:///${PROJECT_ROOT}/../sibling",
"a @ …
```
=> Set PROJECT_ROOT like pdm expects

CHANGELOG.md, docs/guide/tools.md, rye/src/cli/install.rs, rye/src/installer.rs
This lets one install extra dependencies as part of tool installation.
Fixes #323
=> Added --extra-requirement to rye install

CHANGELOG.md, rye/src/cli/add.rs
This fixes `rye add openai-whisper`.
=> Make rye add pick == instead of ~= for single component versions

CHANGELOG.md, rye/src/pyproject.rs
Prompted by finding .pdm-build which contain pyproject.toml files
after building a wheel.
=> workspace: ignore .-directories when searching for projects

CHANGELOG.md, Cargo.lock, docs/guide/config.md, docs/guide/installation.md, docs/guide/shims.md, mkdocs.yml, rye/src/cli/shim.rs, rye/src/config.rs
This adds support for invoking the `python` shim from outside of a rye managed virtualenv. This behavior is disabled by default but turned on by turning it on in the `config.toml`:
```toml
[behavior]
global-python = true
```
Then running `python` will pick up the `.python-version` defined Python or one that is sett in `default.toolchain` in the `config.toml`. Additionally it's possible run `python +3.8` to invoke a Python 3.8 interpreter on the spot.
Fixes #330
=> Add support for global, non venv Python invocations

CHANGELOG.md, rye/src/cli/add.rs
=> Added --pin argument to rye add

CHANGELOG.md, Cargo.lock, rye/Cargo.toml, rye/src/bootstrap.rs, rye/src/cli/add.rs, rye/src/cli/build.rs, rye/src/cli/config.rs, rye/src/cli/init.rs, rye/src/cli/make_req.rs, rye/src/cli/mod.rs, rye/src/cli/pin.rs, rye/src/cli/publish.rs, rye/src/cli/remove.rs, rye/src/cli/run.rs, rye/src/cli/rye.rs, rye/src/cli/shell.rs, rye/src/cli/shim.rs, rye/src/cli/show.rs, rye/src/cli/toolchain.rs, rye/src/cli/tools.rs, rye/src/cli/version.rs, rye/src/installer.rs, rye/src/lock.rs, rye/src/main.rs, rye/src/piptools.rs, rye/src/pyproject.rs, rye/src/sync.rs, rye/src/tui.rs
=> Emit on stdout rather than stderr for most cases

CHANGELOG.md, rye/src/cli/shim.rs
The global shim feature did not work properly on windows because the `.exe` extension was not correctly considered when the shim was intercepted in the lookup.
=> Fix broken global shims on windows

CHANGELOG.md, docs/guide/pyproject.md, rye/src/cli/run.rs, rye/src/pyproject.rs
https://pdm.fming.dev/latest/usage/scripts/#call
=> support `pdm` or pyproject style scripts

rye/src/cli/init.rs
I found this error when running rye init:
Command init: Argument or group 'no-import' specified in 'conflicts_with*' for 'REQUIREMENTS_FILE' does not exist'
and this seems to address it.
This is how clap has specced it: https://github.com/clap-rs/clap/pull/4759#issuecomment-1466585442
=> Fix argument conflicts_with in rye init

rye/src/cli/add.rs, rye/src/cli/remove.rs
Without some restriction, `rye add --path foo` would previously run as a
successful command that does nothing, which is confusing for the user.
Always require >= 1 requirement in add and remove.
Don't allow `rye add --path ./x x y` or similar, these arguments make
sense with one requirement only.
I'm not sure if there is a nicer way of reporting argument errors here
than using `bail!()`.
=> rye add argument checking

rye/src/platform.rs
Check if the python binary exists in `list_known_toolchains`. If not, skip it since it's not a valid python toolchain.
The main scenario related to this issue, is when you execute rye first time which will cause self bootstrap (like `ryn sync`), during the self toolchain download time (this may take a long time with an unstable internet connection), hit ctrl-c to break it, then rerun the command, then you will always got this error:
```
Bootstrapping rye internals
Found a compatible python version: cpython@3.11.3
error: could not sync because bootstrap failed
Caused by:
0: unable to create self venv using /home/■■■■■/.rye/py/cpython@3.11.3/python3
1: No such file or directory (os error 2)
```
This is caused by the `/home/■■■■■/.rye/py/cpython@3.11.3/` is created and is empty in the first …
=> Ensure python exists when find self venv

CHANGELOG.md, rye/Cargo.toml, rye/src/cli/version.rs, rye/src/pyproject.rs
Can read version info when dynamic.
```
dynamic = ["version"]
[tool.hatch.version]
path="src/o/__init__.py"
```
Some tests:
```
➜  o git:(main) ✗ rye version
0.1.0
➜  o git:(main) ✗ rye version 0.2.0
error: unsupported set dynamic version
```
=> Version command can show dynamic version

CHANGELOG.md, Cargo.lock, requirements-dev.lock, requirements.lock, rye/src/bootstrap.rs, rye/src/cli/show.rs, rye/src/installer.rs, rye/src/piptools.rs, rye/src/pyproject.rs
=> Pin down pip for now

rye/src/cli/publish.rs
According to https://github.com/mitsuhiko/rye/issues/373, maybe a bit more clear for the users.
=> chore: clarify the passphrase prompt

rye/src/installer.rs, rye/src/piptools.rs, rye/src/sync.rs
Specify prompt when create venv. The prompt is not used for `rye shell`, but it's usefull for using rye under an IDE like:
=> Set prompt when create venv

rye/src/cli/init.rs
Closes #400 
This is a minor change that attempts to disambiguate *creating* a new project from *initializing* one behind `rye init`.
FWIW `cargo init` and `cargo new` exist. I don't personally have an issue with one `rye init` command, so this PR attempts to preserve that merge by updating verbiage.
=> Update `rye init --help` message

rye/src/pyproject.rs
Fixes error when parsing project version:
```sh
$ cat pyproject.toml |rg version
version = "0.1.0"
```
```sh
$ rye version
error: invalid version: Version ` "0.1.0"` doesn't match PEP 440 rules
```
=> Fix parsing project version

rye/src/cli/rye.rs
The latest commit doesn't build on windows.
Swapping from `if cfg!(...)` to `#[cfg(...)]` fixes it.
=> Fix building on windows

CHANGELOG.md, rye/src/cli/init.rs, rye/src/platform.rs
currently, rye cannot get correctly `user.(email|name)` from `.gitconfig` which using `includeIf` in the file. This PR is to fix this problem. closes #435
=> Improve author detection when includeIf is used

CHANGELOG.md, rye/src/cli/version.rs
Fix https://github.com/mitsuhiko/rye/issues/399#issuecomment-1736693239
```
➜  rye-test git:(main) ✗ rye version
2.1.0
➜  rye-test git:(main) ✗ rye version -b patch
version bumped to 2.1.1
➜  rye-test git:(main) ✗ rye version -b minor
version bumped to 2.2.0
➜  rye-test git:(main) ✗ rye version -b major
version bumped to 3.0.0
```
=> Fix the wrong behavior when bump version

CHANGELOG.md, rye/src/cli/shim.rs
This improves the shim discovery code in two ways:
1. it now prints out a different error when it can't find a python shim vs any other shim
2. it now detects the dummy windows store shim implemented via applink reparse points. This is a very hacky detection and most likely will break at one point but there are no better APIs available.
Fixes #480
=> Detect windows python shim

CHANGELOG.md, rye/src/cli/init.rs
Addresses https://github.com/mitsuhiko/rye/issues/319.
Currently, having scripts works as long as you do `rye sync`.  However, `rye init` does not provide a default script in `pyproject.toml` despite creating a default `__init__.py`.  This PR streamlines the developer init workflow to approximate Rust more closely so that the following works: 
1) `rye init my_project`
2) `rye sync` (after `cd my_project`)
3) `rye run hello` (no manual editing of pyproject.toml needed)
The following is now generated based on the project name: 
Tested locally on a Windows 11 machine.
=> Add default script in pyproject.toml for init

rye/src/cli/init.rs
fix #526
now it succeed to init and sync
```
$ rye init foo-bar
$ cd foo-bar
$ rye sync
...
Installing collected packages: foo-bar
Successfully installed foo-bar-0.1.0
Done!
```
=> fix: default script with name_safe

Cargo.lock, rye/Cargo.toml, rye/src/platform.rs
This PR replace the deprecated `std::env::home_dir()` function by `home::home_dir()` coming from cargo crates which unify the call between platforms. Feel free to close it if it's not relevant or merge it :)
Again thanks for your amazing work !
=> Use `home` cargo crate instead of `simple-home-dir`

CHANGELOG.md, rye/src/bootstrap.rs
This disables revocation checks on windows for the downloader. Plenty other software already doesn't check that anyways, so it seems reasonable to have that as a default to fix download issues with corporate MITM proxies.
Fixes #536
=> Disable revocation checks in downloader on windows

CHANGELOG.md, rye/src/installer.rs
In some cases the tools installer would attempt to symlink things which are not really scripts. This is caused because some python packages have stuff in the bin/scripts folder which is not actually a valid script.
It's possible to work around this oddity at installation time which is what this is now doing.
Fixes #497
=> Fix an issue where some packages would attempt to install weird binaries

CHANGELOG.md, docs/guide/toolchains/index.md, rye/src/cli/fetch.rs, rye/src/cli/init.rs, rye/src/cli/shim.rs
This improves the behavior of `rye fetch`. When invoked without arguments it will now try to fetch the version of the requested Python interpreter. Specifically this makes the following command work even without an installed Python interpreter without manually having to copy paste anything:
```
rye pin 3.8
rye fetch
python
```
The help message is now also adjusted.  Additionally this fixes an issue where the `.python-version` created by the `rye init` command would freeze a to specific version request (usually with architecture). Behavior is now aligned with `rye pin`.
=> Add simplified rye fetch

CHANGELOG.md, rye/src/bootstrap.rs
This moves up the internals to almost the newest versions.  These still support 3.7 as I'm not sure where these are still pulled in.  It does not yet update pip-tools in the tools venv as there are differences in invocation between the version currently used and the latest. As we still support 3.7 a full move cannot be enabled yet without detecting the differences.
=> Update internals to newer versions

CHANGELOG.md, docs/guide/pyproject.md, docs/guide/sync.md, docs/guide/virtual.md, docs/guide/workspaces.md, mkdocs.yml, rye/src/cli/build.rs, rye/src/cli/init.rs, rye/src/cli/publish.rs, rye/src/cli/show.rs, rye/src/lock.rs, rye/src/pyproject.rs
This still creates a project name when initialized with `init`. Taking out version and name is supported by rye but will result in various bugs for third party software so we generate it anyways.
Replaces #309
Fixes #236, #498, #381
=> Added support for virtual projects

CHANGELOG.md, rye/src/bootstrap.rs, rye/src/cli/build.rs, rye/src/cli/fmt.rs, rye/src/cli/lint.rs, rye/src/cli/mod.rs, rye/src/pyproject.rs
This adds two new commands `fmt` (aliased to `format`) and `lint` (aliased to `check`) which invoke ruff. This is similar to how `cargo fmt` and `cargo clippy` invoke `rustfmt` and `clippy` behind the scenes.
I do want to make this configurable in the future, but this is a good starting point.
=> Add ruff powered lint and fmt

CHANGELOG.md, Cargo.lock, rye/Cargo.toml, rye/src/main.rs, rye/src/utils/mod.rs
Restore cursor visibility on ctrl+c.
=> Explicitly handle ctrl-c to restore cursor

CHANGELOG.md, rye/src/cli/fetch.rs
Make `fetch` behavior match the behavior of the shim fully.
Refs #573
=> Improve fetch to be able to fetch all implicit defaults

CHANGELOG.md, rye/src/bootstrap.rs, rye/src/cli/rye.rs, rye/src/utils/mod.rs
Rye now prompts for the default toolchain and persists it in the config when global shims are enabled.
Fixes #573
=> Prompt for default toolchain on installation

CHANGELOG.md, docs/guide/installation.md, rye/src/bootstrap.rs, rye/src/cli/rye.rs, rye/src/utils/mod.rs, rye/src/utils/unix.rs
This automatically adds rye to `PATH` on unix shells.
This commit also fixes a bad internal compatibility reference that can cause confusing during installation.
=> Automatically add to PATH on UNIX shells

Cargo.lock, rye/Cargo.toml, rye/src/sources.rs
This also fixes a build failure, since monotrail-utils depends on a newer version of pep440_rs than we did previously.
=> Update dependencies; fix fallout form pep440_rs change from usize => u64

CHANGELOG.md, Cargo.lock, docs/guide/config.md, docs/guide/faq.md, rye/Cargo.toml, rye/src/config.rs, rye/src/sync.rs, rye/src/utils/mod.rs
By default rye will now mark virtualenvs to not sync to cloud storage (iCloud and Dropbox).
**Todo:**
Fixes #585
=> Added support for marking virtualenvs ignored for cloud sync

CHANGELOG.md, rye/src/piptools.rs, rye/src/sync.rs
It's possible on some platforms that the pip tools bootstrapping happens after the path to pip was looked up. This fixes this which should fix some cases where on first attempt pip tools did not get initialized.
Fixes #594
=> On sync ensure that pip tools are bootstrap in the right order

CHANGELOG.md, docs/guide/commands/pin.md, rye/src/piptools.rs, rye/src/platform.rs, rye/src/pyproject.rs
This changes rye to only prefer the latest version if a compatible already installed toolchain wasn't found. This also fixes an issue where the internal pip-tools venv might be left behind stale when a toolchain was removed.
Fixes #586
=> Select latest compatible installed toolchain

CHANGELOG.md, rye/src/bootstrap.rs
Looks like upgrading unearth fixes an issue with some packages not being added correctly.
After update:
```
$ rye add tensorflow
Added tensorflow>=2.15.0 as regular dependency
```
Fixes #613
=> Bump unearth to newer version

CHANGELOG.md, rye/src/cli/init.rs
Now a project named "2024-foo" will generate a package called "_2024_foo" to make it a valid identifier.
Fixes #610
=> Init fix for projects starting with digits

Cargo.lock, rye/Cargo.toml, rye/build.rs
Unclear if this is a great idea, but this would statically link the vcruntime.
Fixes #617
=> Statically link vcruntime

CHANGELOG.md, rye/src/cli/show.rs, rye/src/config.rs, rye/src/pyproject.rs, rye/src/utils/toml.rs
Add support for inline tables for sources. Now the following two formats are equivalent:
```toml
[[tool.rye.sources]]
name = "test"
url = "https://test.pypi.org/simple/)"
[tool.rye]
sources = [
{ name = "test", url = "https://test.pypi.org/simple/)" }
]
```
Additionally `rye show` now spits out which sources are configured:
```
$ rye show
project: x
...
configured sources:
default (index: https://pypi.org/simple/)
test (index: https://test.pypi.org/simple/)
```
Fixes #485
=> Show sources in rye show and support inline tables

CHANGELOG.md, rye/src/utils/mod.rs
Today we error if xattr removal fails on a virtualenv. That's not ideal because it means the user always sees a warning on an unsupported file system, even if `behavior.venv-mark-sync-ignore` is disabled.
Refs #632
=> No longer error on xattr removal if it fails

rye/src/utils/mod.rs
xattrs need a namespace on Linux, and user is the one that is user-writable. Dropbox seems to document that it will look at this attr.
If I understand correctly, this will not just remove the warning, but the dropbox-ignore should work on Linux.
Fixes #632
Not tested with Dropbox.
=> Use user namespace xattrs on linux and similar

rye/find-downloads.py
This is a full rewrite of find-downloads with the goal to make it a bit more maintainable and readable. I'll leave it to @mitsuhiko if it's actual an improvement. Happy to be told it's not. It certainly quite a bit more verbose.
Things I did:
1. We rewrite the parsing of platform triplets. We only allow hard-coded permutations of arch, platform and environment.
2. We are making heavy use of dataclasses to be clear about the data we store. We use the rust pattern `from_xyz()` to convert a datatype into the respective dataclass
3. We annotate nearly everything with types. Checked in Zed editor to not have type issues.
4. We add "some" unit tests
5. Black + isort formatting
6. We are loggign to stderr, so that we can use stdout to redirect to downloads.inc
Tested by doing
```
$ python3 …
```
=> rewrite find-downloads

CHANGELOG.md, rye/src/sync.rs
The cloud sync marker is now only updated when new virtualenvs are created.
Refs #632
=> Only update venv cloud sync marker when creating virtualenvs

.gitignore
token.txt is used in find-donwloads.py. Let's include any file that is called token.txt, in case people run find-donwloads.py from within the repo.
=> Add token.txt to .gitignore

docs/guide/faq.md
I'm just installing Rye on my Windows 11 machine. I've noticed that the advice for enabling developer mode is out of date for later versions of Windows. 
The [FAQ doc](https://github.com/mitsuhiko/rye/blob/main/docs/guide/faq.md) states that developer mode can be enabled at:
Settings -> Privacy & security -> Security section -> For developers -> Toggle "Developer Mode".
In more modern versions of Windows 11, the steps are: 
Settings -> System -> For developers -> Toggle "Developer Mode".
See my attached screenshots and also the reply by Michael Odi to this [Microsoft support thread discussing developer options](https://answers.microsoft.com/en-us/windows/forum/all/cannot-see-for-developers-option-on-windows-11/20d0be5c-4554-4a14-a37a-5ade77b7be23).
=> Fix out of date Windows Developer Mode instructions

rye/src/cli/config.rs
We use clap's ArgGroup to make any combination of --get, --set, --set-int, --set-bool and --unset
required. If not we print the help.
- **config: require any of --get**
=> Print help when `rye config` is given without any argument

CHANGELOG.md, rye/src/cli/add.rs, rye/src/sources.rs
When `uv` is available, `rye add` now bypasses `unearth`. This leads to more consistent experiences.
At least for when `uv` is used, this should also fix #654
=> Port rye add to uv

rye/src/cli/rye.rs
Using `--yes` for avoiding prompts during installation, Rye will default to use `uv`. I'm not sure if this is intended.
```
rye on  cp-no-prompt-install is 📦 v1.0.0 via 🐍 v3.11.6 via 🦀 v1.76.0 
❯ rm -rf ~/.rye
rye on  cp-no-prompt-install is 📦 v1.0.0 via 🐍 v3.11.6 via 🦀 v1.76.0 
❯ curl -sSf https://rye-up.com/get | RYE_INSTALL_OPTION='--yes' bash
This script will automatically download and install rye (latest) for you.
######################################################################## 100.0%
Welcome to Rye!
This installer will install rye to /Users/chrispryer/.rye
This path can be changed by exporting the RYE_HOME environment variable.
Details:
Rye Version: 0.24.0
Platform: macos (aarch64)
Installed binary to /Users/chrispryer/.rye/shims/rye
Bootstrapping rye internals
Downloading …
```
=> Default to use opt-in behavior for `uv` during no-prompt installation

docs/guide/config.md, rye/src/bootstrap.rs, rye/src/cli/fetch.rs, rye/src/cli/init.rs, rye/src/cli/rye.rs, rye/src/cli/shim.rs, rye/src/config.rs, rye/src/pyproject.rs, rye/src/sync.rs
- Docs: added how to enable the experimental use of `uv`
- Standardize Python capitalization across various CLI messages
- Aligned the CLI message when global shims are not activated with changes in #669
=> Docs: add config setting for uv. CLI: Standardize Python Capitalization, refine some CLI messages

rye/src/config.rs
45ca7b6a1d74441a0aaac2917ba15b8c3583eb00 introduces tests. Some of the tests rely on the presence or absence of the http_proxy env variable respectively. However as tests are run in parallel and env variables are a global program state, this is not safe. We remove the test relying on env variables for now, as it cause random failures in CI.
- **partially revert 45ca7b6a1d74441a0aaac2917ba15b8c3583eb00**
=> partially revert config tests

docs/guide/basics.md
According to the CLI warning, `rye show --installed-deps` is deprecated in favor of `rye list`. This should be reflected in the manual.
=> Replace deprecated `rye show --installed-deps` in documentation

rye/src/cli/rye.rs
This is an RFC for how we handle skipping certain steps independent
from --yes being present. The PR adds the `--modify-path` and
`--no-modify-path` flag that can be used to turn off and on path
modification without prompting the user.  his allows people to do
self-installs such as `rye self install --yes --no-modify-path`.
The goal here is to get fine grained control over the install process
for headless/non-interactive installations. We use `--x`, `--no-x` style
flags inline with popular tools like curl, ripgrep, git, etc.
This should address https://github.com/mitsuhiko/rye/issues/620.
=> Add --modify-path and --no-modify-path to self install

CHANGELOG.md, rye/src/cli/init.rs
The `-q` parameter did not function as intended.
=> Fix quiet flag not working for init

CHANGELOG.md, docs/guide/commands/fetch.md, rye/src/cli/fetch.rs
The arch and os are provided in the version argument: `cpython-x86_64@3.11`
=> Remove unused ARCH argument from fetch

rye/src/sources.rs
Before:
```
❯ rye fetch cpython@3.11.7.lto
error: error while fetching python installation
Caused by:
unknown version cpython@3.11.7
```
After:
```
❯ cargo run --quiet fetch cpython@3.11.7.lto
error: error while fetching Python installation
Caused by:
unknown version cpython@3.11.7.lto
```
=> Add suffix to PythonVersionRequest display

Cargo.lock, rye/Cargo.toml, rye/src/cli/add.rs, rye/src/lock.rs, rye/tests/common/mod.rs, rye/tests/test_sync.rs
This adds the first two snapshot tests for rye. These tests won't work for all platforms yet.
=> Added basic tests

CHANGELOG.md, rye/src/cli/fmt.rs, rye/src/cli/lint.rs, rye/src/utils/mod.rs, rye/src/utils/ruff.rs
`ruff` currently creates a `.ruff_cache` folder in whichever directory it's run from, causing many `.ruff_cache` folders throughout the worktree. Set it to a single fixed location, the workspace root.
=> Set ruff cache dir to workspace root

CHANGELOG.md, rye/src/cli/install.rs
Currently only the latest toolchain will be used when installing tools, while a user may have set things up with a different one. This change uses the default toolchain, unless other options are provided on the command line.
=> Use default toolchain to install tools

CHANGELOG.md, rye/src/cli/mod.rs
This should help debug things.
=> Print uv flag in --version

rye/src/cli/fetch.rs, rye/src/cli/install.rs, rye/src/cli/uninstall.rs
Multiple commands providing identical functionality can be a little confusing; clarify that some are simply aliases.
=> docs: clarify that `rye fetch/install/uninstall` are aliases

docs/guide/sync.md
This is a quick and dirty approach to document some of the limitations in lockfiles.
See #717.
- **docs: document lockfile limitations**
=> document lockfile limitations

docs/guide/installation.md, docs/guide/pyproject.md, notes/metasrv.md, rye/src/cli/mod.rs
I initially noted "instead" twice in an error message, and then went on to look for more occurrences of the word that could be removed to make things a bit easier to read while stil clear.
=> Remove redundant occurrences of "instead"

docs/guide/commands/add.md
Adds an example demonstrating how to use local path dependency for the rye add command.
=> docs: add example for local path dependancy for `rye add`

rye/src/cli/init.rs
Fixes a typo in the description of `rye init --build-system`.
- **fix missing space in init --build-system flag description**
=> fix typo in `rye init --build-system`

CHANGELOG.md, docs/guide/basics.md, rye/src/cli/init.rs, rye/src/templates/LICENSE.txt.j2, rye/src/templates/README.md.j2, rye/src/templates/gitignore.j2, rye/src/templates/lib/default/__init__.py.j2, rye/src/templates/lib/maturin/Cargo.toml.j2, rye/src/templates/lib/maturin/__init__.py.j2, rye/src/templates/lib/maturin/lib.rs.j2, rye/src/templates/pyproject.toml.j2, rye/src/templates/script/default/__init__.py.j2, rye/src/templates/script/default/__main__.py.j2, rye/src/templates/setuptools.py.j2, rye/tests/common/mod.rs, rye/tests/test_init.rs
- **fix missing space in init --build-system flag description**
- **init: add support for --bin**
--lib and --lib-rs,This adds support for three new flags which determine the templates
we generate:
1. We adding --lib, which will generate the standard python library
We no longer generate `[project.scripts]` section and updated
the template.
2. We added --script, which will generate a package with a __main__.py,
__init__.py and an entry to `[project.scripts]`. `__main__.py` follows
semantics found in Python packages such as `ensurepip` and `pip.
3. We added simple tests. Tests do not cover yet `--lib` and `--build-system=maturin`.
4. We added a short section about executable projects to docs/guide/basic.md
5. We moved all in init.rs to a `templates` folder and use `include_str!()`.
=> --script and --lib flags

Cargo.lock, rye/Cargo.toml, rye/src/cli/rye.rs
As discussed in [here](https://github.com/mitsuhiko/rye/pull/731#discussion_r1500264325), shell detection based on the current shell with `whattheshell` does not work with the suggested installation method via the `get.sh` script, since the detected shell will be the one used to run `get.sh`. Therefore, even if the used shell is `fish` or `zsh`, running ` curl https://rye-up.com/get | bash` will not print the note for the fish shell because `bash` will be detected.
The same issue prevents from conditonally adding rye to `.zprofile` for zsh.
This PR changes the shell detection to use `which` to detect if fish or zsh is installed on the system. It further adds a note on how to use rye with zsh.
Closes #728
=> Better shell detection for fish and zsh during installation

CHANGELOG.md, docs/guide/commands/fetch.md, rye/src/bootstrap.rs, rye/src/cli/fetch.rs, rye/src/installer.rs, rye/src/sync.rs, rye/tests/test_toolchain.rs
[indygreg/python-build-standalone](https://github.com/indygreg/python-build-standalone) may recompile an existing Python version in a subsequent release; take, for instance, the [20240224 release](https://github.com/indygreg/python-build-standalone/releases/tag/20240224), which republished Python 3.10.13. As a result, the Python toolchain you've previously downloaded might not be the most current iteration. 
This pull request adds the `--force` flag to the `rye fetch` command, to make a re-fetch of a downloaded version.
=> Add `rye fetch --force` to re-fetch a toolchain

CHANGELOG.md, rye/src/cli/add.rs
It's possible for no build system to be configured.
Fixes #782
=> Fix broken hatchlink detection

.github/workflows/tests.yml, Makefile
I'm sure it's intentional to not run everything in CI. I felt it might be helpful especially for the CLI to fully run.
=> Use 'cargo insta test' in Makefile's test command

rye/tests/common/mod.rs
In #759 I'd like to add a wheels directory as part of the testing resources we're storing in target/debug/rye-test-home.
I've changed RYE_HOME to rye-test-dir/home. I'd add rye-test-dir/wheels in #759.
=> Rename rye-test-home to rye-test-dir

docs/guide/basics.md
I tried generating a project with  below commands like [the documentation](https://rye-up.com/guide/basics/#executable-projects).
```shell
rye init --script my-project
cd my-project
```
However,  the next step occurs an error.
> The [pyproject.toml](https://rye-up.com/guide/pyproject/) will be generated with a [[project.scripts]](https://rye-up.com/guide/pyproject/#projectscripts) section named `hello` that points to the `main()` function of `__init__.py`. After you synchronized your changes, you can run the script with `rye run my-project`.
```shell
rye sync
rye run my-project
error: invalid or unknown script 'my-project'
```
I checked the available commands.
```shell
rye run
hello
python
python3
python3.12
```
I don't think there is a project's name command.
That's why I updated `rye …
=> docs: update script command

.github/workflows/clippy.yml, .github/workflows/python-format.yml, .github/workflows/python-lint.yml, .github/workflows/rustfmt.yml, .github/workflows/spelling.yml, .github/workflows/tests.yml
There's some redundancy in the CI currently.
With this change it should be this on both `main` and PRs (plus manual triggers):
=> Update CI triggers

.github/workflows/python-format.yml, .github/workflows/python-lint.yml, .github/workflows/sync-python-releases.yml, .github/workflows/sync-uv-releases.yml, pyproject.toml
Also remove `.rye` from ruff excludes as it is not added any more by the action
Fixes the workaround introduced in https://github.com/astral-sh/rye/pull/822
=> Bump eifinger/setup-rye from v1 to v2

CHANGELOG.md, rye/src/cli/publish.rs
While working on #759 I noticed that we didn't offer support for dispatching `--skip-existing` from Twine.
```
--skip-existing       Continue uploading files if one already exists. (Only valid when uploading to PyPI. Other
implementations may not support this.)
```
Edit: This PR adds `--skip-existing` to the publish command.
~~This PR adds `--force` (`-f`) which covers dispatch of `--skip-existing`. I landed on *"force"* because I felt it was more generic. `--skip-existing` to me falls under the category of *forcing behavior*. So I decided to start with something more generic to approach this feature.~~
~~I'm kind of curious in general of `--skip-existing`, since, to me (IIUC), it's effectively a swap of an already published package -- which just feels odd to be able to do.~~
I tested …
=> Add `--skip-existing` to publish command

rye/src/bootstrap.rs, rye/src/cli/mod.rs
Inspect the venv marker for the self python environment and report its version in rye --version output.
Example (installed with 3.11.7)
```
> RYE_HOME=xyz ./xyz/shims/rye --version
rye 0.28.0
commit: 0.27.0+8 (2111778b3 2024-02-28)
platform: linux (x86_64)
self-python: cpython@3.11.7
symlink support: true
uv enabled: true
> RYE_HOME=notinstalled ./xyz/shims/rye --version
rye 0.28.0
commit: 0.27.0+8 (2111778b3 2024-02-28)
platform: linux (x86_64)
self-python: not bootstrapped (target: cpython@3.12)
symlink support: true
uv enabled: false
```
=> Report the actual self python version

docs/guide/commands/publish.md, docs/guide/publish.md, rye/src/cli/publish.rs
This is Twine's description of this flag:
```
--skip-existing       Continue uploading files if one already exists. (Only valid when uploading to PyPI. Other
implementations may not support this.)
```
I originally interpreted this as "upload the file anyway" -- which is wrong and sounded odd since being able to replace published packages probably wouldn't be great design for a package repository.
To me this wording is more clear about what this flag actually does.
=> Update publish command's `--skip-existing` description

rye/src/config.rs, rye/tests/test_config.rs
=> Automatically create RYE_HOME in config

CHANGELOG.md, rye/src/cli/add.rs, rye/tests/test_add.rs, rye/tests/test_sync.rs
When `uv` is used `rye add` now retains version and URL if the requirement has version or URL.
Fixes #817
Fixes #833
Fixes #800
=> Retain version/url on rye add

rye/src/cli/shim.rs
The applink detector did not properly null terminate the path. This probably worked by chance.
=> Fix a bug with the applink detector (missing trailing NULL)

CHANGELOG.md, rye/src/main.rs, rye/src/utils/mod.rs, rye/src/utils/panic.rs
Pretty terrible way to do this, but given that various things might write to stdout, that might be the most reliable way.
Fixes #861
=> Trap panics and silence bad pipe errors

CHANGELOG.md, rye/src/cli/rye.rs
After update this will attempt to run `rye init` and the `python` shim in the context of that project. This under all known Rye versions should trigger a python only sync and updating of the internals.
Fixes #859
=> Update self-venv on rye update

CHANGELOG.md, docs/guide/commands/self/update.md, rye/src/cli/rye.rs
fixes https://github.com/astral-sh/rye/discussions/860
=> Rye can update self to a special git branch

rye/src/bootstrap.rs
Fixes a regression that pip-tools was not wiped if the internals are outdated.
Refs #863
=> Fix update of pip-tools on outdated self-venv

CHANGELOG.md, rye/src/cli/test.rs
rye test output format uncorrect
fix #879
=> fix: rye test output format uncorrect

pyproject.toml
rye puts testing Python toolchains inside `target/debug/rye-test-home/py`. When you run `pytest`, it searches `target` and inadvertently picks up Python standard library tests, resulting in thousands of test cases to run. We should ignore `target` when running pytest in rye project.
=> Ignore `target` when running `pytest` in rye

rye/src/cli/add.rs
`Url::from_file_path` returns Err on Windows if the prefix is not a disk prefix (e.g. C:), we can work around this by using `Url.set_path`.
```
rye init --build-system setuptools hello
cd hello
rye add m --path ./m
```
=> Fix `rye add m --path ./m` panic on windows

rye/src/bootstrap.rs, rye/src/cli/add.rs, rye/src/cli/list.rs, rye/src/installer.rs, rye/src/lock.rs, rye/src/pyproject.rs, rye/src/sync.rs, rye/src/utils/mod.rs, rye/src/uv.rs
The pull requests moves all invocations of `uv` to `src/uv.rs`. The invokations are now structured into three main structures: 
- `UvBuilder`, which can be used to create a new instance of a `uv` binary that ensures `uv` exists on disk. 
- `Uv`, which provides operations using `uv` outside of the virtual environment, for example creating a venv, compiling lockfiles ,etc.
- `UvWithVenv`, which must be obtained using `Uv::venv()` to guarantee a venv is available, which encapsulates operations on the venv.
This opens the door to implement the same patterns for `pip-tools` and intorduce a trait to use dynamic dispatching instead of the existing `if/else` structure. If we continue down this path, we can hopefully in the future just do:
```rs
// Create either PipTools or Uv instance, returns …
```
=> uv: move all uv commands to uv.rs

docs/guide/config.md
Fixing the default Pypi index in the config [[source]] part.
`pip install -h` yields
with the http version I get the following error with uv enabled:
After fixing to `https` rye add works without problems
=> FIX: Docs Pypi default link

CHANGELOG.md, rye/src/cli/test.rs
rye test -q behaves like pytest -q -s, but the extra -s (no capture == show all standard output) is surprising.
This seems out of place but I don't know if it was deliberate - I suggest this change.
=> rye test: Don't enable capture=no in quiet mode

docs/guide/docker.md, mkdocs.yml
Hey, I just recently heard about this project, and I love it! I was wondering how to create docker containers and read through the issue (#241) and discussion (#239). I tried out what works and what seems to be clean to me and wrote it down. 
If I understood it correctly, then web apps should (usually) be virtual projects, since they (usually) don't produce a package, so the first part of the guide is a recommendation on how to deal with this case. IMHO "virtual project" isn't the most intuitive name for "doesn't produce a package", and while the documentation on it is alright, it's not very discoverable to me -- I only know about them since I clicked through all the links in the docs. But maybe it's fine to refer to them in the Docker section.
I've refrained from including any `sed …
=> Add Docker instructions

CHANGELOG.md, docs/guide/commands/fetch.md, docs/guide/config.md, docs/guide/toolchains/index.md, rye/src/bootstrap.rs, rye/src/cli/fetch.rs, rye/src/config.rs, rye/src/installer.rs, rye/src/sync.rs, rye/tests/common/mod.rs
This adds support for fetching to specific locations. This can be useful even without installing rye:
```
RYE_NO_AUTO_INSTALL=1 ./rye fetch cpython@3.11 --target-path=./py3.11
```
Going forward `~/.rye/py` will now also no longer have the `install` folder by default to save on space.
=> Remove build info by default and add explicit fetching

CHANGELOG.md, rye/src/cli/rye.rs, rye/src/config.rs
The default is still `pip-tools` but the installer now recommends uv.
=> Installer now recommends uv

CHANGELOG.md, rye/src/bootstrap.rs
Registered toolchain can be a symlink to `python.exe`, before `0.31.0`, we use `py_bin.is_file()` to detect:
https://github.com/astral-sh/rye/blob/c7cbdd955cf494f905e5388e49677149a58028c2/rye/src/bootstrap.rs#L348-L350
Fixes #926
=> Fix `rye fetch` detection of registered toolchain

CHANGELOG.md, rye/src/utils/ruff.rs
These commands produced `ruff --verbose check`  (same for --quiet and same for format) but the verbose/quiet need to come after the subcommand. The command would produce an error (file `check`/`format` does not exist), now it succeeds.
Fixes #956
=> Fix verbose/quiet for rye lint and format

rye/src/pyproject.rs
This change done for its effect on the add command too. We should ignore build-system for rye purposes, if the project is configured as virtual. The warning is useful because other tools might not handle this the same way - it is best to remove the unused configuration(?)
=> Ignore build-system configuration for virtual projects

docs/guide/commands/self/completion.md
corrects a syntax mistake when calling `eval` in the documentation for zsh shell completion
=> Correct syntax when calling `eval` on completion command documentation

rye/src/installer.rs, rye/src/uv.rs
Ensures that we rebuild any local packages when you run with `-f`.
Closes https://github.com/astral-sh/rye/issues/984.
```
❯ cargo run install ../uv/scripts/packages/black_editable -f
Compiling rye v0.33.0 (/Users/crmarsh/workspace/rye/rye)
Finished dev [unoptimized + debuginfo] target(s) in 1.18s
Running `target/debug/rye install ../uv/scripts/packages/black_editable -f`
Resolved 1 package in 0.91ms
Built black @ file:///Users/crmarsh/workspace/uv/scripts/packages/black_editable                                                                                                                                                           Downloaded 1 package in 132ms
Installed 1 package in 0.60ms
+ black==0.1.0 (from file:///Users/crmarsh/workspace/uv/scripts/packages/black_editable)
```
=> Add `--refresh` argument on `-f`

docs/guide/basics.md
This PR corrects the run command which will error if black is not given a directory to check. Refined wording to reinforce "add-install-run" steps.
=> DOC: correct black run command and refine text

CHANGELOG.md, rye/src/cli/init.rs
Let initial files like pyproject.toml, .gitignore, \_\_init\_\_.py etc all keep their trailing newline so that they finish with a (single) newline.
Fixes #950
=> Preserve trailing newline in templates

rye/src/platform.rs
`pyenv` allows comments in `.python-version` files, so Rye will now skip commented-out lines.
Note that not _all_ tools support this. For example, [`mise`](https://github.com/jdx/mise) does not.
Closes #1032.
=> Allow comments in `.python-version`

CHANGELOG.md, rye/src/bootstrap.rs, rye/src/cli/build.rs, rye/src/utils/mod.rs, rye/src/uv.rs
The `build` package supports uv since version 1.2.0 - it can use either uv or pip as installer.
The main way to use it would be to install `build[uv]` but rye already has uv installed separately, build will find it on the path as a fallback, so this can work for rye.
build is implicitly tested by test_publish.
Relates to #668
=> Use uv in rye build when enabled

rye/src/cli/add.rs
(Feature request) Adding dev-deps is rather common, and it's nice to have a short version for this, so I suggest `-d` for this (long option is `--dev`).
Example:
```
rye add -d pytest
Added pytest>=8.1.1 as dev dependency
```
Survey: pdm uses pdm add -d. Poetry uses poetry add -D (but says it's deprecated, use --group=dev instead.)
=> Add short version add -d for rye add --dev

docs/guide/config.md, docs/guide/sync.md, rye/src/config.rs
I think `uv` is now stable enough to serve as the default backend for Rye. Users can explicitly opt-out with, e.g., `rye config --set-bool behavior.use-uv=false`, to fall back to the `pip-tools` backend.
Suggested here: https://twitter.com/mitsuhiko/status/1783853343502160290
=> Flip uv to the default Rye backend

rye/src/cli/rye.rs
Fixes https://github.com/astral-sh/rye/issues/1024
Currently:
* When installation calls  `ensure_self_venv_with_toolchain` to bootstrap rye internals it would pass the `toolchain_version_request` variable as the version to install
* If the `RYE_TOOLCHAIN_VERSION` env var is not set, then the value of `toolchain_version_request` remains None
* During installation, `prompt_for_default_toolchain` is called to prompt the user for a version to select, asking the user `"Which version of Python should be used as default toolchain?"`
* This function stores the user's selection in the `config_doc` TOML configuration and returns nothing
* The user's toolchain version selection is thus never passed to the internals bootstrapping call
Changes:
* This fix makes `toolchain_version_request` mutable so …
=> Fix Rye not using user-chosen toolchain as default during installation

docs/guide/commands/lock.md, docs/guide/commands/sync.md, docs/guide/virtual.md, rye/src/cli/shim.rs, rye/src/cli/show.rs, rye/src/cli/sync.rs
Similar to https://github.com/astral-sh/rye/pull/165 and https://github.com/astral-sh/rye/pull/167, there are some more instances of synched/synching which should be changed to synced/syncing to make the docs consistent.
=> Fix some spellings

rye/src/bootstrap.rs, rye/tests/test_ruff.rs
Noticed ruff was a bit old and was missing a lot of rules, leading to a lot of "unused noqa".
I unfortunately dont have the rust knowledge to improve this, but it would be nice if we could update ruff independently of rye and still run it using `rye lint/fmt`.
Thanks for this amazing tool! Gave it a shot today and really really enjoyed playing around with it and testing it out. Currently porting some of my projects to use it!
=> Bump boostrap ruff to 0.4.4

rye/src/utils/toml.rs
Closes #1083
A trailing newline is only added if there are dependencies or comments in the array.
=> Fix TOML array formatting

rye/src/utils/mod.rs
Executables compiled with [Cosmopolitan](https://justine.lol/cosmopolitan/index.html) libc runtime have a `.com` extension on Windows. This includes cosmo-ified Python binaries.
Example [here](https://github.com/astral-sh/rye/files/15366179/python.zip).
=> Discover cosmo-ified (`.com`) binaries on Windows

rye/src/cli/rye.rs
Ensures that if the user runs in `InstallMode::NoPrompts`, we still write the default (`use-uv = true`) to the configuration file.
Closes https://github.com/astral-sh/rye/issues/1081.
```
rye on  charlie/def:main
❯ cargo run self install -y
Finished dev [unoptimized + debuginfo] target(s) in 0.08s
Running `target/debug/rye self install -y`
Welcome to Rye!
This installer will install rye to /Users/crmarsh/.rye
This path can be changed by exporting the RYE_HOME environment variable.
Details:
Rye Version: 0.34.0
Platform: macos (aarch64)
Installed binary to /Users/crmarsh/.rye/shims/rye
Updated self-python installation at /Users/crmarsh/.rye/self
The rye directory /Users/crmarsh/.rye/shims was not detected on PATH.
It is highly recommended that you add it.
Added to PATH.
note: for this to …
```
=> Write `use-uv = true` in no-prompt mode

.github/workflows/clippy.yml, .github/workflows/rustfmt.yml, .github/workflows/spelling.yml, .github/workflows/tests.yml
Removes all the Node.js 16 versions from the CI runs
=> Bump actions/checkout to v4

rye/src/cli/add.rs, rye/src/cli/lock.rs, rye/src/cli/remove.rs, rye/src/cli/sync.rs, rye/src/cli/test.rs, rye/src/sync.rs
We weren't passing `--pre` when auto-syncing after `rye `add`.
Closes https://github.com/astral-sh/rye/issues/1102
=> Enforce `--pre` when auto-syncing

README.md
The site is down due to DNS issues, changing this in the interim.
=> Temporarily change installer location

README.md, docs/.includes/curl-to-bash-options.md, docs/.includes/quick-install.md, docs/CNAME, docs/community.md, docs/guide/faq.md, rye/src/bootstrap.rs, rye/src/cli/rye.rs, rye/src/cli/shim.rs, rye/src/uv.rs
We're having issues with `rye-up.com`. We're trying to recover it but need to work with the registrar. In the interim, I'm going to move the docs and installers to `rye.astral.sh`. When `rye-up.com` is recovered, we can redirect, either from `rye.astral.sh` to `rye-up.com` or vice versa.
Closes #1111.
=> Move from `rye-up.com` to `rye.astral.sh`

README.md
On latest Ubuntu current install instructions result with an error:
```
user@user-laptop:~$ curl -sSf https://rye.astral.sh/get | sh
sh: 2: set: Illegal option -o pipefail
```
While using the instructions on the official website: https://rye.astral.sh/ work as expected.
This PR updates the README.md version to match
=> Fix install instructions on README.md for mac/linux

docs/guide/commands/lock.md, docs/guide/commands/sync.md, docs/guide/pyproject.md, rye/src/pyproject.rs, rye/src/sync.rs
Please note: I haven't written any Rust before, but just wanted this feature hence thought I'd try submitting a PR for this. I've essentially tried to mimic the code regarding the `--with-sources` feature. I'm not sure how to compile and test locally (so welcome any info on this - and if helpful I would be happy to test this locally and get back to confirm if this works).
All thoughts/help/feedback etc. very welcome, and no worries if this feature is not useful. 
- Adds ability to specify option to generate hashes via the pyproject.toml (similar to https://rye.astral.sh/guide/pyproject/#toolryelock-with-sources).
- Updates doc regarding the `--generate-hashes` option too.
- Added [`+++ 0.35.0`](https://github.com/astral-sh/rye/pull/1129/files#diff-8ea7c706930a01df775defe815afe2478a41699e0a …
=> Add ability to specify option to generate hashes within pyproject.toml

rye/src/config.rs, rye/src/pyproject.rs
improve config.toml error msg
when I write a unvalid config.toml
```toml
[[sources]]
url = "https://company.internal/simple/"
```
the before msg is very strange: `error: expected name`
after: `error: bad config.toml syntax,expected source.name`
=> improve config.toml error msg

requirements-dev.lock, requirements.lock
It looks like `pyyaml==6.0.0` has a faulty source distribution that we can't build (`pip install pyyaml==6.0.0 --no-cache --force-reinstall --no-binary pyyaml` fails). But `pyyaml==6.0.1` works as expected. The documentation seems to build in a musl container, so it has to build from source.
=> Upgrade pyyaml to v6.0.1

rye/src/cli/install.rs, rye/src/installer.rs, rye/src/lock.rs, rye/src/sync.rs, rye/src/uv.rs
When calling `uv pip {install,sync}`, the `keyring-provider` argument doesn't get passed, even though `uv` supports these arguments for both.
We already have the functionality implemented for `uv pip compile`, so just extend the support to these.
Tested locally for both commands, seems to work fine.
=> Pass keyring-provider to uv sync and install

rye/src/bootstrap.rs
Closes https://github.com/astral-sh/rye/issues/1180.
=> Upgrade twine version

rye/src/pyproject.rs
https://github.com/astral-sh/rye/blob/main/docs/guide/sources.md?plain=1#L131
The documentation refers to verify-ssl to avoid ssl verification, but during parsing, it refers to verify_ssl. This PR will allow the installation of packages from non-SSL PyPI repositories.
If the documentation needs to be corrected instead of the source code, please let me know, and I will commit the changes.
=> fix verify-ssl option parsing problem

README.md, docs/.includes/quick-install.md
Was just downloading Rye to try it out and got a bit annoyed by the confusing download links (like `x64 Intel Windows`  - I have an AMD CPU, and it obviously doesn't matter), so I updated them to more standard terms, although there are several options to update them to, so feel free to ask for / make changes).
I also think it might be a good idea to consider dropping the Windows x86 (32-bit) builds, as Windows 11 doesn't even support x86, and Windows 10 EOL is next year (plus, I doubt there are many Windows 10 users using the 32-bit version. Especially developers), and it just confuses newcomers with an additional option to pick from.
=> Update Docs Description for Download Options

rye/src/cli/remove.rs
=> Add short version `-d` for `rye remove --dev`

rye/src/cli/fetch.rs, rye/src/cli/install.rs, rye/src/cli/uninstall.rs
Remove redundant information about `toolchain fetch` being an alias of `toolchain fetch`.
=> Remove redundant alias information from CLI

rye/src/bootstrap.rs, rye/src/cli/build.rs, rye/src/uv.rs
Today, `rye build` uses the bootstrapped (or "self") environment, which means built wheels reflect the version from the bootstrapped environment, rather than the user's Python preference.
This PR changes `build` to instead create an ephemeral build environment based on the requested Python version (then install and run `build` in that environment).
Creating and populating that ephemeral build environment is extremely fast with uv; there's virtually no overhead.
Closes https://github.com/astral-sh/rye/issues/1152.
Closes https://github.com/astral-sh/rye/issues/1248.
- Ran `../rye/target/debug/rye build` from a directory with `.python-version` of `3.11`.
- Verified that Python 3.11 was used.
=> Respect `.python-version` in Rye builds

rye/src/cli/run.rs, rye/tests/common/mod.rs, rye/tests/test_scripts.rs
=> Make rye run print script list to stdout

rye/src/cli/add.rs, rye/src/cli/rye.rs, rye/src/installer.rs, rye/src/pyproject.rs
Closes https://github.com/astral-sh/rye/issues/1012.
=> Always write `--index-url` before `--extra-index-url`

rye/src/cli/shim.rs
This check can be subtly incorrect on case-insensitive filesystems (e.g., NTFS). Seems easiest to just make the whole comparison case-insensitive.
Closes https://github.com/astral-sh/rye/issues/1284.
=> Use case-insensitive comparison for detecting `rye.exe`

docs/guide/toolchains/cpython.md
NITS: I fixed the license for readline in the documentation to GPLv3.
cf. https://tiswww.case.edu/php/chet/readline/rltop.html
> Readline is free software, distributed under the terms of the [GNU General Public License, version 3](http://www.gnu.org/licenses/gpl.html).
cf. https://gregoryszorc.com/docs/python-build-standalone/main/running.html#licensing
> Most licenses are fairly permissive. Notable exceptions to this are GDBM and readline, which are both licensed under GPL Version 3.
=> Fix documentation for readline license

docs/guide/commands/add.md
Just fixing a small typo with the text: `requiement` -> `requirement`
=> fix: requiement -> requirements typo in add.md

rye/src/lock.rs, rye/tests/test_sync.rs
Closes https://github.com/astral-sh/rye/issues/1349.
=> Respect exclusions when generating hashes

rye/src/cli/toolchain.rs
Using `rye toolchain remove` now lists all tools that use a specific toolchain.
This eliminates the Whac-a-Mole game of reiterating through the `rye toolchain remove blabla` command in order to actually remove it.
```bash
$ rye install black --quiet --python 3.11.7
$ rye toolchain remove 3.11.7
error: toolchain cpython@3.11.7 is still in use by tool black
$ rye install ruff --quiet --python 3.11.7
$ rye toolchain remove 3.11.7
error: toolchain cpython@3.11.7 is still in use by tools: black, ruff
```
_(Side note: Rust isn't my main d2d language, feel free to comment on coding style and unidiomatic code)_
=> List all existing tool references on `rye toolchain remove`

docs/guide/workspaces.md
This PR edits the copy in `workspaces.md` adding small improvements in use of prepositions, punctuation, etc.
Addresses #1396
=> Edit wording in `workspaces.md`

rye/src/bootstrap.rs
Resolves: #1426
This pull request includes an update to the compatibility range for the supported Python versions in the `is_self_compatible_toolchain` function.
* [`rye/src/bootstrap.rs`](diffhunk://#diff-5e3b4dd9c9d72709e7551b50ad0bb8933e251e3f7ea71370a13637900c1b349cL285-R287): Updated the supported Python versions to include cpython 3.13.
=> Fix compatibile toolchain

.github/workflows/release.yml
The `macos-12` runners are deprecated: https://github.com/astral-sh/rye/actions/runs/12244443745
=> Upgrade runners to `macos-14`

rye/src/bootstrap.rs, rye/tests/test_ruff.rs
CI checks fail for an unrelated reason, see #1458
=> Bump bundled Ruff version to 0.9.6

.github/workflows/clippy.yml, .github/workflows/tests.yml, rust-toolchain.toml
Use a consistent Rust version so tests and lint errors, etc., don't start failing sporadically with each release.
=> Set Rust toolchain in `rust-toolchain.toml`

.github/workflows/release.yml, rust-toolchain.toml
It seems like Cross doesn't yet support 1.85.
=> Attempt to build against Rust 1.84
